wanno/annotations/urls.py
from django.conf.urls import patterns, url, include

from annotations import handler

urlpatterns = patterns('',
    url(r'^p/(?P<path>.*)$', handler.annotations, name='index'),                       
    url(r'search', handler.annotations, name='search'),                       
    url(r'^id/(?P<path>.*)/(?P<number>\d)$', handler.annotation, name='id'),                       
    #url(r'.*', handler.index, name='index'),
    #url(r'^$', handler.index, name='index'),
    #url(r'^html/(?P<path>.*)$', views.showpage, name='showhtml'),
    #url(r'^create/(?P<path>.*)$', views.create, name='create'),
    #url(r'^edit/(?P<path>.*)$', views.edit, name='edit'),
)

wanno/gitview/urls.py
from django.conf.urls import patterns, url, include

from gitview import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^commit/(?P<commit_id>[a-z0-9]+)$', views.detail, name='detail'),
    url(r'^update$', views.update_git, name='update'),
)

wanno/wanno/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


from django.conf import settings ## DEBUG


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'wanno.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^wiki/', include('wiki.urls', namespace="wiki")),
    url(r'^git/', include('gitview.urls', namespace="git")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^annotations/', include("annotations.urls", namespace="annotations")),
)


if settings.DEV_SERVER: ## DEBUG !!!
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_PATH}),
    )

wanno/wiki/urls.py
from django.conf.urls import patterns, url, include

from wiki import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^html/(?P<path>.*)$', views.showpage, name='showhtml'),
    url(r'^create/(?P<path>.*)$', views.create, name='create'),
    url(r'^edit/(?P<path>.*)$', views.edit, name='edit'),
)

wanno/annotations/models.py
from django.db import models

# Create your models here.

wanno/gitview/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

wanno/wiki/models.py
from django.db import models

# Create your models here.
class Page(models.Model):
    """A wiki page"""
    name = models.CharField(max_length=2000)
    path = models.CharField(max_length=2000)
    repository = models.CharField(max_length=2000)
    ## Should check here whether the name is valid...
    ## AND UNIQUE!
    text = models.TextField()
    pub_date = models.DateTimeField('date published')
    

wanno/annotations/views.py
from django.shortcuts import render

# Create your views here.

wanno/gitview/views.py
import os
import tempfile
import binascii

from django.shortcuts import render
from django.http import HttpResponse
from git import Repo, Commit
try:
    import pypandoc
    parser = pypandoc.convert
except ImportError:
    def parser(*args,**kargs):
        return " <br/> <br/>USE PYPANDOC FOR PARSING <br/> <br/> <code>"+"<br /> ".join(args)+"</code>"
FOLDER_NAME = 'test'
URL = "git@gitlab.com:geeklhem/testrepo.git"
FILE_NAME = 'testtext.org'

def critic2html(text):
    text = text.replace("{--", "<del>")
    text = text.replace("--}", "</del>")
    text = text.replace("{++", "<add>")
    text = text.replace("++}", "</add>")
    text = text.replace("{>>", '<span class="comment">')
    text = text.replace("<<}", '</span>')
    text = text.replace("{==", "<mark>")
    text = text.replace("==}", "</mark>")
    text = text.replace("{==", "<mark>")
    text = text.replace("==}", "</mark>")
    text = text.replace("~>", '</ins><del class="sub">')
    text = text.replace("~~}", '</del>')
    text = text.replace("{~~", '<ins class="sub">')
    return text

def open_repo(name=FOLDER_NAME, url=URL):
    path = os.path.join(tempfile.gettempdir(), name)
    if not os.path.exists(path):
        repo = Repo.clone_from(url, path)
    else:
        repo = Repo(path)

    return path, url, repo

def index(request):
    path, url, repo = open_repo()
    context = {"url": url,
               "commits":  repo.iter_commits(),
               'path': path}
    return render(request, 'gitview/index.html', context)

def update_git(request):
    _, _, repo = open_repo()
    a = repo.remotes.origin.pull()
    return HttpResponse(a)


def detail(request, commit_id):
    path, url, repo = open_repo()
    commit = Commit(repo, binascii.a2b_hex(commit_id))
    tree = commit.tree
    fmt = os.path.basename(FILE_NAME).split(".")[-1]
    context = {"url": url,
               "commit_id":commit_id,
               "fmt":fmt,
               "filename":FILE_NAME,
               "file":parser(critic2html(tree[FILE_NAME].data_stream.read()), 'html', format=fmt),
               'path': path}
    return render(request, 'gitview/commit.html', context)

wanno/wiki/views.py
#-*-coding:utf-8-*-
# wanno wanno wiki modules
# By the wanno team, 2014-2016
# GPLv3+

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.utils import timezone

import parser
import json

from wiki.models import Page
import gitmanager

def index(request):
    """Returns the list of pages"""
    t = "Here are the wiki pages.<br />"
    t += ', '.join([p.name for p in Page.objects.all()])
    return HttpResponse(t)

def showpage(request, path):
    """The main page processor. It renders the page when they get created"""
    if request.method == 'POST' and request.is_ajax(): # Handle the edition case
        # Should migrate code from the edit function here
        try:
            p = Page.objects.get(name=path)
        except Exception:
            return HttpResponse(json.dumps({'status': 'error', 'text' : 'The document {} is not found, strange'.format(path)}))

        # Get the data
        html = json.loads(request.body)["html"]
        annotations = json.loads(request.body)["ann"]
        coordinates = parser.extract_coordinates(html)
        # - match the annotations with the coordinates to create a usable annotator json
        
        # - pypandoc

        
        # - edit the file, save the HTML copy and annotations, and commit.
        gitmanager.write_to_file(p.path, content=None, html=html, annotations=annotations, url=p.repository)

        return HttpResponse(json.dumps({'status': 'ok', 'text' : 'The document has been saved, nice'}))
    else: # Display the HTML page
        try:
            p = Page.objects.get(name=path)
        except Exception:
            return render(request, 'wiki/html/notfound.html', {'name': path, 'path': path})


        template = loader.get_template('wiki/html/page.html')

        content = ""
        try:
            content = gitmanager.get_content(p.path, url=p.repository, commit_id=None)
        except Exception as ex:
            print(ex)
        if not len(content):
            try:
                content = gitmanager.get_content(p.path+".html", url=p.repository, commit_id=None)
            except Exception as ex:
                print(ex)
                content = "Problem"
        return render(request, 'wiki/html/page.html', {'name': p.name,
                                                       'text': parser.parse(content)['text'],
                                                       'path': path,
                                                       'pub_date' : p.pub_date})


def create(request, path, txt="No text has been added yet, edit the page to add stuff"):
    """Create a page in the database"""
    p = Page(name=path, text=txt, pub_date=timezone.now())
    p.save()
    return HttpResponseRedirect(reverse("wiki:showhtml", args=(path,)))

def edit(request, path):
    """Show a form to edit the page, and handle the edition"""
    p = get_object_or_404(Page, name=path)
    if request.POST.has_key('text'):
        # Edit the database
        p.text = request.POST["text"]
        p.save()
        return HttpResponseRedirect(reverse("wiki:showhtml", args=(path,)))
    else:
        return render(request, 'wiki/html/edit.html', {'name': p.name,
                                                       'path': path,
                                                       'text' : p.text,
                                                       'pub_date': p.pub_date})

wanno/gitview/templates/gitview/commit.html
<h1> Git repo visualisation </h1>
<p> {{ url }} cloned in {{path}} / {{commit_id}}, file: {{filename}} (markup={{fmt}})</p>

{% autoescape off %}
{{file}}
{% endautoescape %}

<footer>
  <p> {{ url }} cloned in {{path}} / {{commit_id}},
file: {{filename}} (markup={{fmt}})</p>
</footer>

wanno/gitview/templates/gitview/index.html
<h1> Git repo visualisation </h1>
{{ url }} cloned in {{path}}

<h3>Commit list:</h3>

<ul>
{% for commit in commits %}
<li><a href="commit/{{commit.hexsha}}">{{commit.hexsha |slice:":10"}} </a>{{commit.message |truncatewords:"10"}} by <em>{{ commit.author.name }}</em> on {{commit.committed_date}}</li>
{% endfor %}
</ul>

wanno/wiki/templates/wiki/html/edit.html
This is not valid HTML
<h1>{{ name }}</h1>

<form action="{% url 'wiki:edit' path %}" method="post">
  {% csrf_token %}

  <textarea name="text">
    {{ text }}
  </textarea>

  <input type="submit" value="Edit" />
</form>

Powered by the Zuper wiki-annotator processor.
Page created on {{ pub_date }}

wanno/wiki/templates/wiki/html/notfound.html
This is not valid HTML
<h1>Page does not exist (yet)</h1>

<p>
  The page {{ name }} does not exist. Do you want to <a href="{% url 'wiki:create' path %}">create it</a>? With an initial file (not implemented yet)?
</p>

Powered by the Zuper wiki-annotator processor.

wanno/wiki/templates/wiki/html/page.html
{% load staticfiles %}
<!doctype html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'wiki/html/style.css' %}" />
    <script src="{% static 'wiki/lib/jquery-2.2.3.min.js' %}"></script>
    <script src="{% static 'wiki/lib/annotator.1.2.7/annotator.min.js' %}"></script>
    <script src="{% static 'wiki/lib/annotator.1.2.7/annotator.store.min.js' %}"></script>
    <script src="{% static 'wiki/lib/jquery.cookie.js' %}"></script>
    <script src="{% static 'wiki/lib/wanno.js' %}"></script>
    <script src="{% static 'wiki/lib/csrf.js' %}"></script>
    <link rel="stylesheet" href="{% static 'wiki/lib/annotator.1.2.7/annotator.min.css' %}">
  </head>
  <body>
    
    This is not valid HTML
    <h1>{{ name }}</h1>
    <div class="alert">Let's display some information here</div>
    <div id="annotations">
      <div id="annotatedtext">
	<p>
	  {{ text }}
	</p>
      </div>
    </div>

    
    <div class="tools">
      <p> You always can <a href="{% url 'wiki:edit' path %}">edit</a> this page</p>
      <p> You always also <a id="submit" href="#">submit</a> this page (with jquery :)</p>

    </div>
    <div class="footer">
      ______________<br/>
      Powered by the <em>Zuper</em> wiki-annotator processor.
      Page created on {{ pub_date }}. Last edited on [tbc].
    </div>
  </body>
</html>